// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmEd2vuvxrv0mr3K8O9mYv7fEg4uTaNrw',
    appId: '1:217996878180:web:2e7e46f409e068ef85da71',
    messagingSenderId: '217996878180',
    projectId: 'sign-in-with-firebase-4ffe3',
    authDomain: 'sign-in-with-firebase-4ffe3.firebaseapp.com',
    storageBucket: 'sign-in-with-firebase-4ffe3.appspot.com',
    measurementId: 'G-H9VRR406B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_pxaTb8HE8VhnIsjRFEd4r4yjHgMxK5o',
    appId: '1:217996878180:android:96cfdc9bb2636f8d85da71',
    messagingSenderId: '217996878180',
    projectId: 'sign-in-with-firebase-4ffe3',
    storageBucket: 'sign-in-with-firebase-4ffe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCecciA3grTJbiizd2D2eVe1TerCtewFM',
    appId: '1:217996878180:ios:34ce30495643971485da71',
    messagingSenderId: '217996878180',
    projectId: 'sign-in-with-firebase-4ffe3',
    storageBucket: 'sign-in-with-firebase-4ffe3.appspot.com',
    iosBundleId: 'com.example.firebaseSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmEd2vuvxrv0mr3K8O9mYv7fEg4uTaNrw',
    appId: '1:217996878180:web:c65f6a8a137a265c85da71',
    messagingSenderId: '217996878180',
    projectId: 'sign-in-with-firebase-4ffe3',
    authDomain: 'sign-in-with-firebase-4ffe3.firebaseapp.com',
    storageBucket: 'sign-in-with-firebase-4ffe3.appspot.com',
    measurementId: 'G-45EN9Q43JH',
  );
}
